version: '3.7'

# Services
services:
  # Redis Cache Service
  redis:
    platform: linux/x86_64
    image: redis
    container_name: redis
    expose:
      - 6379
    networks:
      - default
  # Nginx Service
  nginx:
    build: ./.docker/nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
      - 8000:8000
      - 8080:8080
      - 3000:3000
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1 remote_autostart=1
    volumes:
      - ./www/php:/var/www/php:ro
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./.docker/ssl/:/etc/nginx/ssl/:ro
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      default:
        aliases:
          - local.dlhf.vn
          - sso-local.dlhf.vn
          - services-local.dlhf.vn
          - biz-local.dlhf.vn
          - shop-local.dalathasfarm.com
          - tools-local.dalathasfarm.com
          - esb-local.dalathasfarm.com
          - picktool-local.dalathasfarm.com
    depends_on:
      - php
    links:
      - redis

  # PHP Service
  php:
    build: ./.docker/php
    container_name: php
    expose:
        - 9000
        - 9003
    working_dir: /var/www/php
    volumes:
      - ./www/php:/var/www/php
    networks:
      - default
    depends_on:
      - mysql
    links:
      - redis



  # MySQL Service
  # mariadb:
  mysql:
    # image: mariadb:10.5
    platform: linux/x86_64
    image: mysql:8
    container_name: mysql
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      # - mariadbdata:/var/lib/mysql:delegated
      - ./.docker/mysql/mysqldata:/var/lib/mysql
      # - ./.docker/conf:/etc/mysql
      - ./.docker/mysql/mysql-files:/var/lib/mysql-files
    networks:
      - default

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:5
  #   ports:
  #     - 8080:80
  #   environment:
  #     PMA_HOST: mysql
    # depends_on:
      # - mysql:
        # condition: service_health y

# Volumes
volumes:
  mysqldata:
  mariadbdata:

#Network
networks:
  default:
    driver: bridge



